import React from 'react';

const StatsSection = () => {
  return (
    <section className="bg-[#1E2A36] text-white  py-24 my-8 rounded-corners">
      <div className="container mx-auto px-6 md:px-10 max-w-[90%]">
        <h2 className="header-h1">Key Statistics</h2>
        <h3 className="header-h2">Let&apos;s close the loop in the Nordics together.</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-center">
          <div className="px-4">
            <div className="header-h2">4.6m tons</div>
            <p className="text-p1">Waste generated by Swedish businesses annually.</p>
          </div>

          <div className="px-4">
            <div className="header-h2">Only 49%</div>
            <p className="text-p1">Municipal waste in Europe is recycled.</p>
          </div>

          <div className="px-4">
            <div className="header-h2">10-30%</div>
            <p className="text-p1">Avg. cost savings.</p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default StatsSection;
